# Generated by Django 3.1.14 on 2026-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
    ]
