# Generated by Django 3.1.7 on 2021-04-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='original_author_id',
        ),
    ]
