# Generated by Django 3.1.14 on 2026-01-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='correspondence',
        ),
        migrations.RemoveField(
            model_name='review',
            name='merits',
        ),
        migrations.RemoveField(
            model_name='review',
            name='presentation',
        ),
        migrations.AddField(
            model_name='review',
            name='abstract',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'abstract'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstract', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='illustrations',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'illustrations'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illustrations', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='interpretation',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'interpretation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpretation', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'language'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='layout',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'layout'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='length',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'length'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='length', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='nomenclature',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'nomenclature'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclature', to='papers.grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'title'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='papers.grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='tag',
            field=models.CharField(choices=[('originality', 'Czy jest to oryginalne opracowanie wśród publikacji z tego zakresu?'), ('layout', 'Czy układ opracowania jest zadowalający?'), ('length', 'Czy objętość  opracowania jest adekwatna do jego treści?'), ('language', 'Czy język oraz sposób przedstawienia wyników jest jasny dla czytelnika?'), ('nomenclature', 'Czy oznaczenia oraz terminologia odpowiadają standardom z określonej dyscypliny nauki?'), ('interpretation', 'Czy według Pani(a) opinii interpretacja wyników oraz wnioski są logiczne i uzasadnione?'), ('abstract', 'Czy streszczenie zawiera wystarczające oraz użyteczne informacje?'), ('title', 'Czy tytuł artykułu jest jasny i odpowiada jego treści?'), ('illustrations', 'Czy rysunki i tabele są potrzebne oraz odpowiednie?'), ('final_grade', 'Wniosek końcowy (rekomendacja do celów wydawniczych): praca')], max_length=16),
        ),
    ]
