# Generated by Django 3.1.7 on 2021-04-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20210412_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='correspondence',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'correspondence'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='papers.grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='final_grade',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'final_grade'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade', to='papers.grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='merits',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'merits'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merits', to='papers.grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='originality',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'originality'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originality', to='papers.grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='presentation',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag': 'presentation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation', to='papers.grade'),
        ),
    ]
