# Generated by Django 3.2.25 on 2026-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20251216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='statement_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
