# Generated by Django 3.1.7 on 2021-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_original_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclub',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
