# Generated by Django 3.1.14 on 2026-01-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20251216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
