# Generated by Django 3.1.7 on 2021-04-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_notificationperiod_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
