# Generated by Django 3.1.7 on 2021-03-10 16:11

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20210310_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors_string',
        ),
        migrations.AlterField(
            model_name='paper',
            name='club',
            field=models.ForeignKey(default=papers.models.StudentClub.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='papers.studentclub'),
        ),
    ]
