# Generated by Django 3.1.14 on 2026-01-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_statement_reminder_sent'),
        ('papers', '0003_paper_author_phone'),
    ]

    operations = [
    ]
