# Generated by Django 3.1.14 on 2026-01-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20260115_2107'),
        ('papers', '0004_merge_20260121_2009'),
    ]

    operations = [
    ]
