# Generated by Django 3.1.14 on 2026-02-04 10:41

from django.db import migrations, models
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_merge_20260124_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, max_length=512, upload_to=papers.models.paper_directory_path, validators=[papers.models.validate_file_size]),
        ),
    ]
