# Generated by Django 3.1.7 on 2021-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_auto_20210310_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageseen',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageseen',
            name='reader',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageSeen',
        ),
    ]
