# Generated by Django 3.1.14 on 2026-02-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20260204_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
