# Generated by Django 3.1.14 on 2026-03-20 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0007_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='editors',
            field=models.ManyToManyField(blank=True, max_length=3, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
