# Generated by Django 3.1.14 on 2026-03-20 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0008_paper_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
