# Generated by Django 3.1.14 on 2026-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_message_nullable_participants'),
        ('papers', '0010_auto_20260320_1730'),
    ]

    operations = [
    ]
