services:
  pg:
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  django-qcluster:
    build: .
    command: python manage.py qcluster
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./media:/app/media:rw

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: always
    ports:
      - "3000:3000"

volumes:
  pgdata: {}
