# pull official base image
FROM python:3.9.6-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache python3-dev musl-dev jpeg-dev zlib-dev libjpeg && \
	apk add --no-cache build-base freetype-dev && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h

# set work directory
WORKDIR /usr/src/app/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt ./requirements.txt

# install dependencies
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY ./src/ ./

RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py loaddata announcement grades groups notificationperiod studentclubs