# Generated by Django 3.1.14 on 2023-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
