# Generated by Django 3.1.14 on 2023-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='number',
            field=models.CharField(default='nie podano', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='street',
            field=models.CharField(default='nie podano', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.CharField(default='nie podano', max_length=100),
        ),
    ]
