# Generated by Django 3.1.7 on 2021-03-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0002_downloadedfile_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedfile',
            name='author_id',
            field=models.SmallIntegerField(),
        ),
    ]
