name: Staging

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            set -e
          
            cd /home/kni/prace_kol/staging/StronaPraceKol
            git stash
            git checkout dev
            git pull
            docker compose -p kola_staging up --build -d
            
            cd ../
            echo "$(date): service staging deployed successfully" >> deploy-log.txt
            
            docker system prune -a -f
