name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            set -e
          
            cd /home/kni/prace_kol/StronaPraceKol
            git stash
            git checkout main
            git pull
            docker compose up --build -d
            
            cd ../
            echo "$(date): service deployed successfully" >> deploy-log.txt
            
            docker system prune -a -f
